const FAMILY_LEDGER_SHEET_NAMES = {
  accounts: 'Accounts',
  transactions: 'Transactions',
  balances: 'Balances',
  commodities: 'Commodities',
  prices: 'Prices',
  attachments: 'Attachments',
  issues: 'Issues',
};

const FAMILY_LEDGER_PAGE_SIZE = 1000;

const FAMILY_LEDGER_DOCTOR_TARGET_REGISTRY = Object.freeze([
  Object.freeze({
    targetPrefix: 'transactions/',
    visibleSheetName: FAMILY_LEDGER_SHEET_NAMES.transactions,
  }),
  Object.freeze({
    targetPrefix: 'accounts/',
    visibleSheetName: FAMILY_LEDGER_SHEET_NAMES.accounts,
  }),
  Object.freeze({
    targetPrefix: 'balanceAssertions/',
    visibleSheetName: FAMILY_LEDGER_SHEET_NAMES.balances,
  }),
  Object.freeze({
    targetPrefix: 'attachments/',
    visibleSheetName: FAMILY_LEDGER_SHEET_NAMES.attachments,
  }),
]);

const FAMILY_LEDGER_ACCOUNT_ROOT_MARKERS = {
  Assets: '[A]',
  Liabilities: '[L]',
  Expenses: '[X]',
  Income: '[I]',
  Equity: '[Q]',
};

const FAMILY_LEDGER_HEADER_ROLE_COLORS = {
  readonly: '#d1d5db',
  editable: '#dbeafe',
  action: '#fde68a',
  system: '#e5e7eb',
};

function buildSheetConfig_(key, name, columnLayout, options) {
  const headers = Object.keys(columnLayout);
  const columns = headers.reduce(function(result, header, index) {
    result[header] = Object.freeze({ index: index, column: index + 1 });
    return result;
  }, {});
  return Object.freeze({
    key: key,
    name: name,
    headers: Object.freeze(headers),
    columns: Object.freeze(columns),
    columnLayout: Object.freeze(columnLayout),
    hiddenHeaders: Object.freeze((options && options.hiddenHeaders) || []),
    protectedHeaders: Object.freeze((options && options.protectedHeaders) || []),
    issueHeader: (options && 'issueHeader' in options) ? options.issueHeader : 'issues',
    issueColor: (options && options.issueColor) || '#fee2e2',
  });
}

const FAMILY_LEDGER_SHEET_REGISTRY = Object.freeze({
  transactions: buildSheetConfig_('transactions', FAMILY_LEDGER_SHEET_NAMES.transactions, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Click to open the Edit/Delete Transaction sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 180,
      role: 'system',
      note: 'Technical transaction resource name used by the client.',
      alignment: 'left',
      header_text: 'resource name',
    },
    transaction_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only transaction date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      quickFilter: 'date',
      insertionOrder: true,
      header_text: 'date',
    },
    payee: {
      width: 300,
      role: 'editable',
      note: 'Editable payee. Applies to the whole transaction.',
      alignment: 'left',
      wrapStrategy: 'CLIP',
      header_text: 'payee (from/to)',
    },
    narration: {
      width: 200,
      role: 'editable',
      note: 'Editable narration. Normal text = transaction narration; italic = posting-specific narration.',
      alignment: 'left',
      header_text: 'narration (remarks)',
    },
    narration_source: {
      width: 95,
      role: 'system',
      note: 'Technical narration ownership marker used by the client.',
      alignment: 'left',
      header_text: 'narration source',
    },
    source_account_name: {
      width: 230,
      role: 'readonly',
      note: 'Read-only source account.',
      alignment: 'left',
      wrap: false,
      quickFilter: 'account',
      header_text: 'source account name',
    },
    destination_account_name: {
      width: 280,
      role: 'editable',
      note: 'Editable destination allocation account.',
      alignment: 'left',
      wrap: false,
      quickFilter: 'account',
      validation: 'account',
      header_text: 'destination account name',
    },
    symbol: {
      width: 55,
      role: 'readonly',
      note: 'Read-only commodity symbol.',
      alignment: 'center',
      header_text: 'symbol',
    },
    amount: {
      width: 85,
      role: 'editable',
      note: 'Editable allocation amount. Lowering it creates a split for imported transactions.',
      alignment: 'right',
      numberFormat: '#,##0.00',
      header_text: 'amount',
    },
    split_off_amount: {
      width: 85,
      role: 'action',
      note: 'Action field. Enter an amount to split, or x / - to delete a split row.',
      alignment: 'right',
      header_text: 'split',
    },
    tags: {
      width: 100,
      role: 'editable',
      note: 'Editable comma-separated tags for this transaction.',
      alignment: 'left',
      header_text: 'tags',
    },
    issues: {
      width: 600,
      role: 'system',
      note: 'Derived ledger doctor issues merged by transaction.',
      alignment: 'left',
      wrap: false,
      wrapStrategy: 'OVERFLOW',
      formulaManaged: true,
      header_text: 'issues',
    },
    has_cost_price: {
      width: 60,
      role: 'system',
      note: 'True when any posting in this transaction group has a cost or price annotation. Used to guard inline edits.',
      header_text: 'has cost price',
    },
  }, {
    hiddenHeaders: ['resource_name', 'narration_source', 'has_cost_price'],
    protectedHeaders: ['resource_name', 'transaction_date', 'source_account_name', 'symbol'],
  }),
  balances: buildSheetConfig_('balances', FAMILY_LEDGER_SHEET_NAMES.balances, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Check to open the edit sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 220,
      role: 'system',
      note: 'Technical balance assertion resource name used by the client.',
      alignment: 'left',
      header_text: 'resource name',
    },
    assertion_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only assertion date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      quickFilter: 'date',
      insertionOrder: true,
      header_text: 'assertion date',
    },
    account: {
      width: 320,
      role: 'readonly',
      note: 'Read-only account.',
      alignment: 'left',
      wrap: false,
      quickFilter: 'account',
      header_text: 'account',
    },
    amount: {
      width: 110,
      role: 'readonly',
      note: 'Read-only asserted amount.',
      alignment: 'right',
      numberFormat: '#,##0.00',
      header_text: 'amount',
    },
    symbol: {
      width: 55,
      role: 'readonly',
      note: 'Read-only commodity symbol.',
      alignment: 'center',
      header_text: 'symbol',
    },
    issues: {
      width: 600,
      role: 'system',
      note: 'Derived ledger doctor issues linked by balance assertion resource name.',
      alignment: 'left',
      wrap: false,
      wrapStrategy: 'OVERFLOW',
      formulaManaged: true,
      header_text: 'issues',
    },
  }, {
    hiddenHeaders: ['resource_name'],
    protectedHeaders: ['resource_name'],
  }),
  accounts: buildSheetConfig_('accounts', FAMILY_LEDGER_SHEET_NAMES.accounts, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Click to open the Edit/Delete Account sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 180,
      role: 'system',
      note: 'Technical resource name used by the client.',
      alignment: 'left',
      header_text: 'resource name',
    },
    account_name: {
      width: 320,
      role: 'editable',
      note: 'Visible account label used in the Transactions sheet.',
      alignment: 'left',
      wrap: false,
      quickFilter: 'account',
      header_text: 'account name',
    },
    effective_start_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only account opening date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      header_text: 'effective start date',
    },
    effective_end_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only account closing date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      header_text: 'effective end date',
    },
    issues: {
      width: 600,
      role: 'system',
      note: 'Derived ledger doctor issues linked by account resource name.',
      alignment: 'left',
      wrap: false,
      wrapStrategy: 'OVERFLOW',
      formulaManaged: true,
      header_text: 'issues',
    },
  }, {
    hiddenHeaders: ['resource_name'],
    protectedHeaders: ['resource_name', 'effective_start_date', 'effective_end_date'],
  }),
  commodities: buildSheetConfig_('commodities', FAMILY_LEDGER_SHEET_NAMES.commodities, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Click to open the Edit sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 180,
      role: 'system',
      header_text: 'resource name',
    },
    symbol: {
      width: 80,
      role: 'readonly',
      note: 'Commodity symbol.',
      alignment: 'left',
      insertionOrder: true,
      header_text: 'symbol',
    },
    ticker: {
      width: 120,
      role: 'readonly',
      note: 'Market ticker used for price fetching, e.g. NESN.SW, USDCHF=X.',
      alignment: 'left',
      header_text: 'ticker',
    },
  }, { issueHeader: null, hiddenHeaders: ['resource_name'], protectedHeaders: ['resource_name'] }),
  prices: buildSheetConfig_('prices', FAMILY_LEDGER_SHEET_NAMES.prices, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Click to open the Edit/Delete Price sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 200,
      role: 'system',
      note: 'Technical price resource name used by the client.',
      alignment: 'left',
      header_text: 'resource name',
    },
    price_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only price date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      insertionOrder: true,
      header_text: 'price date',
    },
    base_symbol: {
      width: 80,
      role: 'readonly',
      note: 'Read-only base commodity symbol.',
      alignment: 'left',
      header_text: 'base symbol',
    },
    quote_amount: {
      width: 110,
      role: 'readonly',
      note: 'Read-only price per unit of base in quote currency.',
      alignment: 'right',
      numberFormat: '#,##0.0000',
      header_text: 'quote amount',
    },
    quote_symbol: {
      width: 80,
      role: 'readonly',
      note: 'Read-only quote currency symbol.',
      alignment: 'left',
      header_text: 'quote symbol',
    },
  }, {
    issueHeader: null,
    hiddenHeaders: ['resource_name'],
    protectedHeaders: ['resource_name', 'price_date', 'base_symbol', 'quote_amount', 'quote_symbol'],
  }),
  attachments: buildSheetConfig_('attachments', FAMILY_LEDGER_SHEET_NAMES.attachments, {
    edit: {
      width: 40,
      role: 'action',
      note: 'Click to open the Edit/Delete Attachment sidebar.',
      alignment: 'center',
      checkbox: true,
      header_text: 'edit',
    },
    resource_name: {
      width: 200,
      role: 'system',
      note: 'Technical attachment resource name used by the client.',
      alignment: 'left',
      header_text: 'resource name',
    },
    attachment_date: {
      width: 95,
      role: 'readonly',
      note: 'Read-only attachment date.',
      alignment: 'left',
      numberFormat: 'yyyy-mm-dd',
      quickFilter: 'date',
      insertionOrder: true,
      header_text: 'attachment date',
    },
    account: {
      width: 280,
      role: 'readonly',
      note: 'Read-only account.',
      alignment: 'left',
      wrap: false,
      quickFilter: 'account',
      header_text: 'account',
    },
    original_filename: {
      width: 300,
      role: 'readonly',
      note: 'Read-only filename. Hyperlinked to document URL when available.',
      alignment: 'left',
      header_text: 'original filename',
    },
    status: {
      width: 120,
      role: 'readonly',
      note: 'Read-only attachment status (e.g. stored, pending_upload).',
      alignment: 'left',
      header_text: 'status',
    },
    issues: {
      width: 600,
      role: 'system',
      note: 'Derived ledger doctor issues linked by attachment resource name.',
      alignment: 'left',
      wrap: false,
      wrapStrategy: 'OVERFLOW',
      formulaManaged: true,
      header_text: 'issues',
    },
  }, {
    hiddenHeaders: ['resource_name'],
    protectedHeaders: ['resource_name', 'attachment_date', 'account', 'original_filename', 'status'],
  }),
  issues: buildSheetConfig_('issues', FAMILY_LEDGER_SHEET_NAMES.issues, {
    target: {
      width: 220,
      role: 'system',
      note: 'Technical resource name of the affected entity.',
      alignment: 'left',
      header_text: 'target',
    },
    navigate: {
      width: 300,
      role: 'readonly',
      note: 'Click to navigate to the affected row in the source sheet.',
      alignment: 'left',
      wrapStrategy: 'CLIP',
      formulaManaged: true,
      header_text: 'navigate',
    },
    issue_codes: {
      width: 200,
      role: 'readonly',
      note: 'Issue code identifiers.',
      alignment: 'left',
      header_text: 'issue codes',
    },
    issues_text: {
      width: 500,
      role: 'readonly',
      note: 'Full issue descriptions.',
      alignment: 'left',
      wrap: false,
      wrapStrategy: 'OVERFLOW',
      header_text: 'issues text',
    },
  }, {
    issueHeader: null,
    hiddenHeaders: ['target'],
    protectedHeaders: ['target', 'navigate', 'issue_codes', 'issues_text'],
  }),
});
