function onOpen() {
  const ui = SpreadsheetApp.getUi();
  const devMenu = ui.createMenu('Developer Settings')
    .addItem('Sync Ledger', 'syncLedger')
    .addItem('Reset Sheet Layouts', 'resetSheetLayouts')
    .addSeparator()
    .addItem('API Settings', 'showApiSettings')
    .addItem('Test Connection', 'testFamilyLedgerConnection');
  const otherEntityMenu = ui.createMenu('Add Other Entity')
    .addItem('Add Balance Assertion', 'showAddBalanceAssertion')
    .addItem('Add Account', 'showAddAccount')
    .addItem('Add Commodity', 'showAddCommodity')
    .addItem('Add Attachment', 'showAddAttachment')
    .addItem('Add Price', 'showAddPrice')
  ui.createMenu('Family Ledger')
    .addItem('Quick Filter', 'showQuickFilter')
    .addSeparator()
    .addItem('Add Transaction', 'showAddTransaction')
    .addSubMenu(otherEntityMenu)
    .addSeparator()
    .addItem('Import Data', 'showImportDialog')
    .addSeparator()
    .addItem('Create Report', 'showCreateReportDialog')
    .addSeparator()
    .addItem('Sheet Settings', 'showSheetSettings')
    .addItem('Importer Settings', 'showImporterSettings')
    .addSeparator()
    .addSubMenu(devMenu)
    .addToUi();
}
