const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
  {
    ignores: ['node_modules/**'],
  },
  js.configs.recommended,
  {
    files: ['Code.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.es2022,
        BigInt: 'readonly',
        HtmlService: 'readonly',
        PropertiesService: 'readonly',
        ScriptApp: 'readonly',
        SpreadsheetApp: 'readonly',
        UrlFetchApp: 'readonly',
        Utilities: 'readonly',
        console: 'readonly',
        // Constants defined in Constants.js, shared across all script files.
        FAMILY_LEDGER_SHEET_NAMES: 'readonly',
        FAMILY_LEDGER_PAGE_SIZE: 'readonly',
        FAMILY_LEDGER_TRANSACTION_HEADERS: 'readonly',
        FAMILY_LEDGER_ACCOUNTS_HEADERS: 'readonly',
        FAMILY_LEDGER_DOCTOR_ISSUES_HEADERS: 'readonly',
        FAMILY_LEDGER_ACCOUNT_ROOT_MARKERS: 'readonly',
        FAMILY_LEDGER_TRANSACTION_COLUMN_LAYOUT: 'readonly',
        FAMILY_LEDGER_COLUMN_ROLE_COLORS: 'readonly',
        FAMILY_LEDGER_TRANSACTION_ISSUE_ROW_COLOR: 'readonly',
        // Functions defined in extracted files (ApiClient, Accounts, Decimal, Doctor, Layout, SheetIO, Utils).
        apiFetchJson_: 'readonly',
        applyAccountsSheetLayout_: 'readonly',
        applyAccountValidationToRowNumbers_: 'readonly',
        applyTransactionSheetLayout_: 'readonly',
        areTransactionRowsEquivalentForRefresh_: 'readonly',
        buildAccountDisplayEntries_: 'readonly',
        buildApiError_: 'readonly',
        buildApiUrl_: 'readonly',
        canUpdateTransactionRowsInPlace_: 'readonly',
        cloneTransactionSheetRow_: 'readonly',
        compareDecimalStrings_: 'readonly',
        debugLog_: 'readonly',
        ensureAccountIssueFormulas_: 'readonly',
        ensureTransactionIssueFormulas_: 'readonly',
        fetchFamilyLedgerPagedResource_: 'readonly',
        findTransactionRowNumbers_: 'readonly',
        getActiveTransactionGroupFromSheet_: 'readonly',
        getFamilyLedgerApiToken_: 'readonly',
        getFamilyLedgerBaseUrl_: 'readonly',
        getOrCreateSheet_: 'readonly',
        getRequiredFamilyLedgerApiToken_: 'readonly',
        getTransactionHeaderColumnIndex_: 'readonly',
        getTransactionNameForRow_: 'readonly',
        isContiguousRowNumbers_: 'readonly',
        loadAccountNameMap_: 'readonly',
        loadAccountsFromApi_: 'readonly',
        maskToken_: 'readonly',
        mergeFetchedDoctorIssuesIntoRows_: 'readonly',
        negateDecimalString_: 'readonly',
        normalizeApiToken_: 'readonly',
        normalizeBaseUrl_: 'readonly',
        normalizeDecimalString_: 'readonly',
        normalizeTransactionDate_: 'readonly',
        readTransactionSheetRow_: 'readonly',
        readTransactionSheetRowsByNumbers_: 'readonly',
        refreshDoctorIssueSheets_: 'readonly',
        replaceTransactionRowsInSheet_: 'readonly',
        requireTransactionSheet_: 'readonly',
        resolveAccountResourceName_: 'readonly',
        runUserAction_: 'readonly',
        setFieldValuesForRowNumbers_: 'readonly',
        setTransactionSheetRows_: 'readonly',
        subtractDecimalStrings_: 'readonly',
        sumDecimalStrings_: 'readonly',
        parseDateString_: 'readonly',
        uniqueNonBlankValues_: 'readonly',
        updateTransactionRowsInPlace_: 'readonly',
        writeSheet_: 'readonly',
        writeTransactionSheetRow_: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': [
        'error',
        {
          varsIgnorePattern:
            '^(onOpen|handleTransactionEdit|setFamilyLedgerBaseUrl|setFamilyLedgerApiToken|showFamilyLedgerSettings|testFamilyLedgerConnection|syncFamilyLedgerAccounts|syncFamilyLedgerTransactions|pushActiveTransaction|resetSheetLayouts|showImportDialog|getImportersForDialog|getAccountsForDialog|runImportFromDialog)$',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
];
