services:
  api:
    volumes:
      - ./export:/export

  fava:
    image: yegle/fava:latest
    restart: unless-stopped
    command: ["--host", "0.0.0.0", "--port", "5000", "/export/ledger.beancount"]
    ports:
      - "5000:5000"
    volumes:
      - ./export:/export
